# Generated by Django 6.0.1 on 2026-01-17 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('shoulders', 'Shoulders'), ('legs', 'Legs')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-Vegetarian'), ('eggetarian', 'Eggetarian'), ('supplement', 'Supplement')], max_length=20)),
                ('age_group', models.CharField(choices=[('18-36', '18-36 Years'), ('36-60', '36-60 Years')], max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('height_min', models.IntegerField(help_text='Height in inches')),
                ('height_max', models.IntegerField(help_text='Height in inches')),
                ('weight_min', models.IntegerField(help_text='Weight in kg')),
                ('weight_max', models.IntegerField(help_text='Weight in kg')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_calories', models.IntegerField()),
                ('total_protein', models.IntegerField(help_text='in grams')),
                ('total_carbs', models.IntegerField(help_text='in grams')),
                ('total_fat', models.IntegerField(help_text='in grams')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance', models.BooleanField(default=False, help_text='Gym attendance')),
                ('diet_followed', models.BooleanField(default=False, help_text='Diet plan followed')),
                ('workout_completed', models.BooleanField(default=False, help_text='Workout completed')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('target_zone', models.CharField(help_text='e.g., Upper Chest, Long Head', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('body_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='fitness.bodypart')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('dinner', 'Dinner')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('calories', models.IntegerField()),
                ('protein', models.IntegerField(help_text='in grams')),
                ('carbs', models.IntegerField(help_text='in grams')),
                ('fat', models.IntegerField(help_text='in grams')),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='fitness.dietplan')),
            ],
        ),
    ]
