# Generated by Django 6.0.1 on 2026-01-29 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='subscription_active',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='subscription_expires_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='fitness.gym'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
    ]
