# Generated by Django 6.0.1 on 2026-01-29 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_remove_gym_pan_number_remove_gym_subscription_active_and_more'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipplan',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='member',
            name='members_gym_id_400d8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='member',
            name='members_phone_c64f9d_idx',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='photo',
            new_name='profile_image',
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('gym', 'phone')},
        ),
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALFYEARLY', 'Half Yearly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberattendance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='memberattendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='members.member'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='duration',
            field=models.CharField(choices=[('MONTHLY', '1 Month'), ('QUARTERLY', '3 Months'), ('HALFYEARLY', '6 Months'), ('YEARLY', '1 Year'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='fitness.gym'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='memberattendance',
            table='member_attendance',
        ),
        migrations.RemoveField(
            model_name='member',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
    ]
